# Generated by Django 3.0.4 on 2020-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('Canada', 'Canada')], default='USA', max_length=100),
        ),
    ]
