# Generated by Django 3.0.4 on 2020-03-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='expires',
            new_name='expires_at',
        ),
    ]
