# Generated by Django 3.0.4 on 2020-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_auto_20200318_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='If omitted, will be set to time at creation plus the value specified in settings.DEFAULT_ENGAGEMENT_EXPIRATION'),
        ),
    ]
